/-  *wick
/+  *test, *wick, nym=mnemonyms
/*  english  %txt  /fil/wordlists/english/txt
=>
|%
++  mock-nym
  ^-  @t
  '.obtains.adapts.gazelles.unite.dessert.descend.behold.foreseen.remarks.devolve.regains.comprise'
::
++  mock-ship
  ^-  ship
  (~(ship me:nym [.y 128 english]) mock-nym)
::
++  mock-rot
  ^-  @ud
  1
::
++  mock-path
  ^-  path
  (stab '/https/example.com')
::
++  mock-keys
  (pit:nu:cric:crypto 512 0x1f %b ~)
::
++  mock-seed
  ^-  seed:jael
  [mock-ship mock-rot sec:ex:mock-keys ~]
::
++  mock-sig
  ^-  @uxJ
  0x77e.96c4.a01a.bc9b.2eba.01a3.6524.b619.53ac.e01b.567f.c03e.c8fc.375b.dbe7.142e.79cf.ecf2.71b3.0ee1.fe57.c0b3.a09b.a093.a6a1.5361.0cd9.2668.01ef.6054.2edb.a616
::
++  mock-pubkey
  ::  Fixture public key generated by scripts/gen-mock-signed-wire.py.
  ^-  pass
  %+  can  3
  :~  [1 'b']
      [32 0xdea5.dc8b.fb0e.8eeb.5439.fd58.b607.aa8a.0dc2.dc15.daea.9449.e9b3.9240.fe6b.0443]
      [32 0]
  ==
::
++  mock-unsigned-wick
  ^-  wick
  [%7 mock-ship mock-rot .y mock-path 0x0]
::
++  mock-signed-wick
  ^-  wick
  [%7 mock-ship mock-rot .y mock-path mock-sig]
::
++  mock-content-sig
  ^-  @uxJ
  0xb30.972e.148d.bef4.ef7f.b4f9.77a5.119b.b6b5.f46a.d75f.2834.c393.a716.b104.1ad1.b3cc.3301.1079.987b.085f.8d0d.fde5.ed06.3817.0261.9b9d.ce0c.8ea3.36cc.287b.9f01
::
++  mock-content-wick
  ^-  wick
  [%7 mock-ship mock-rot .n mock-path mock-content-sig]
::
++  mock-unsigned-wire
  ^-  cord
  %-  crip
  ;:  welp
    (trip 'wire://')
    (slag 1 (trip mock-nym))
    (trip '/https/example.com')
  ==
::
++  mock-signed-wire
  ^-  cord
  %-  crip
  ;:  welp
    (trip 'wire://')
    (slag 1 (trip mock-nym))
    (trip '/8BEBAC9odHRwcy9leGFtcGxlLmNvbRam2y5UYO8BaCbZDGFToaaToJugs8BX_uEOs3Hy7M95LhTn21s3_Mg-wH9WG-CsUxm2JGWjAboum7waoMSWfgc')
  ==
::
++  mock-content-wire
  ^-  cord
  %-  crip
  ;:  welp
    (trip 'wire://')
    (slag 1 (trip mock-nym))
    (trip '/cBEBAC9odHRwcy9leGFtcGxlLmNvbQGfeyjMNqOODM6dm2ECFzgG7eX9DY1fCHuYeRABM8yz0RoEsRank8M0KF_XavS1tpsRpXf5tH_v9L6NFC6XMAs')
  ==
--
::
|%
::
++  test-wire-to-wick-signed
  %+  expect-eq
    !>  mock-signed-wick
  !>  (wire-to-wick mock-signed-wire)
::
++  test-wire-to-wick-unsigned
  %+  expect-eq
    !>  mock-unsigned-wick
  !>  (wire-to-wick mock-unsigned-wire)
::
++  test-wire-to-wick-content
  %+  expect-eq
    !>  mock-content-wick
  !>  (wire-to-wick mock-content-wire)
::
++  test-wick-to-wire-signed
  %+  expect-eq
    !>  mock-signed-wire
  !>  (wick-to-wire mock-signed-wick)
::
++  test-wick-to-wire-unsigned
  %+  expect-eq
    !>  mock-unsigned-wire
  !>  (wick-to-wire mock-unsigned-wick)
::
++  test-roundtrip-signed
  %+  expect-eq
    !>  mock-signed-wick
  !>  (wire-to-wick (wick-to-wire mock-signed-wick))
::
++  test-roundtrip-unsigned
  %+  expect-eq
    !>  mock-unsigned-wick
  !>  (wire-to-wick (wick-to-wire mock-unsigned-wick))
::
++  test-verify-wick-signed
  %+  expect-eq
    !>  .y
  !>  (verify-wick mock-signed-wick `mock-pubkey ~)
::
++  test-make-and-verify-wick
  =/  made=wick  (make-wick .y mock-seed mock-path ~)
  %+  expect-eq
    !>  .y
  !>  (verify-wick made `pub:ex:mock-keys ~)
::
++  test-make-and-verify-wick-content
  =/  content=octs  [11 'hello world']
  =/  made=wick  (make-wick .n mock-seed mock-path `content)
  %+  expect-eq
    !>  .y
  !>  (verify-wick made `pub:ex:mock-keys `content)
::
++  test-make-and-verify-wick-fine-content
  =/  content=octs  (fine-octs [%txt 'hello world'])
  =/  made=wick  (make-wick .n mock-seed mock-path `content)
  %+  expect-eq
    !>  .y
  !>  (verify-wick made `pub:ex:mock-keys `(fine-octs [%txt 'hello world']))
::
++  test-reject-wick-with-wrong-content
  =/  content=octs  [11 'hello world']
  =/  made=wick  (make-wick .n mock-seed mock-path `content)
  %+  expect-eq
    !>  .n
  !>  (verify-wick made `pub:ex:mock-keys `(fine-octs [%txt 'hello world']))
::
++  test-reject-unsigned-wick
  %+  expect-eq
    !>  .n
  !>  (verify-wick mock-unsigned-wick `mock-pubkey ~)
::
++  test-reject-wick-without-key
  %+  expect-eq
    !>  .n
  !>  (verify-wick mock-signed-wick ~ ~)
::
++  test-reject-wick-with-empty-path
  %+  expect-eq
    !>  .n
  !>  (verify-wick `wick`[%7 mock-ship mock-rot .y ~ mock-sig] `mock-pubkey ~)
::
++  test-reject-wick-with-zero-rotation
  %+  expect-eq
    !>  .n
  !>  (verify-wick `wick`[%7 mock-ship 0 .y mock-path mock-sig] `mock-pubkey ~)
::
++  test-reject-wick-with-oversized-rotation
  %+  expect-eq
    !>  .n
  !>  (verify-wick `wick`[%7 mock-ship 65.536 .y mock-path mock-sig] `mock-pubkey ~)
::
++  test-reject-wick-with-oversized-path
  =/  long=path  /https/[(reap 40 `@ta`'0123456789')]
  %+  expect-eq
    !>  .n
  !>  (verify-wick `wick`[%7 mock-ship mock-rot .y long mock-sig] `mock-pubkey ~)
::
++  test-reject-contentful-wick-without-content
  %+  expect-eq
    !>  .n
  !>  (verify-wick mock-content-wick `mock-pubkey ~)
::
++  test-reject-path-only-wick-with-content
  %+  expect-eq
    !>  .n
  !>  (verify-wick mock-signed-wick `mock-pubkey `(fine-octs [%txt 'hello world']))
--
